sudo: false

language: python
python:
  - '2.7'
  - '3.3'
  - '3.4'
  - pypy

install:
  - pip install -r requirements.txt
  - pip install -r requirements.remote.txt
  - pip install -r requirements.robotshell.txt
  - pip install zetup[commands]
  - pip install pytest
  - pip install tox
  - zetup install

script:
  - zetup pytest
  - py.test test
  - zetup tox
